  [[main]]
  name = "首页"
  identifier = "home"
  weight = 100
  url = "/zh"

  [[main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/zh/post/"

  [[main]]
  name = "项目"
  weight = 300
  identifier = "portfolio"
  url = "/zh/portfolio/"

  [[main]]
  name = "关于我们"
  weight = 400
  identifier = "about"
  url = "/zh/about/"

  [[main]]
  name = "友链"
  weight = 600
  identifier = "contact"
  url = "/zh/friends/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/zh/imprint/"